[package]
name = "containers"
version = "0.0.1"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.97"
nvim-oxi = { version = "0.5.1", features = ["neovim-0-10"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
